Repository geomechanics/mpm, pull requests merged in 2022-09, with the labels that each got.

#70 [Compile] SIGSTKSZ fix and add arm64 support
  external/catch.hpp
Labels: enhancement

#71 [Bugfix] Free surface detection for nonlocal elements
  include/cells/cell.h
  include/cells/cell.tcc
  include/elements/2d/quadrilateral_bspline_element.h
  include/elements/2d/quadrilateral_element.h
  include/elements/2d/quadrilateral_gimp_element.h
  include/elements/2d/quadrilateral_lme_element.h
  include/elements/2d/triangle_element.h
  include/elements/2d/triangle_lme_element.h
  include/elements/3d/hexahedron_bspline_element.h
  include/elements/3d/hexahedron_element.h
  include/elements/3d/hexahedron_gimp_element.h
  include/elements/3d/hexahedron_lme_element.h
  include/elements/3d/tetrahedron_element.h
  include/elements/element.h
  include/mesh/mesh_multiphase.tcc
  tests/cells/cell_test.cc
  tests/elements/hexahedron_bspline_element_test.cc
  tests/elements/hexahedron_element_test.cc
  tests/elements/hexahedron_gimp_element_test.cc
  tests/elements/hexahedron_lme_element_test.cc
  tests/elements/quadrilateral_bspline_element_test.cc
  tests/elements/quadrilateral_element_test.cc
  tests/elements/quadrilateral_gimp_element_test.cc
  tests/elements/quadrilateral_lme_element_test.cc
  tests/elements/tetrahedron_element_test.cc
  tests/elements/triangle_element_test.cc
  tests/elements/triangle_lme_element_test.cc
Labels: bug, enhancement

#75 [Bugfix] Swap status and cell_id for better HDF5 experience
  include/particles/pod_particles/pod_particle.h
Labels: bug

#73 [Fluid] Add a fix in nonlocal free-surface detection algorithm
  include/linear_solvers/linear_solvers/krylov_petsc.tcc
  include/mesh/mesh.h
  include/mesh/mesh_multiphase.tcc
  include/solvers/mpm_explicit_twophase.h
  include/solvers/mpm_explicit_twophase.tcc
  include/solvers/mpm_implicit.h
  include/solvers/mpm_semi_implicit_navierstokes.h
  include/solvers/mpm_semi_implicit_navierstokes.tcc
  include/solvers/mpm_semi_implicit_twophase.h
  include/solvers/mpm_semi_implicit_twophase.tcc
Labels: enhancement

#74 [B-Spline] Kernel correction nearby boundary
  include/cells/cell.tcc
  include/elements/2d/quadrilateral_bspline_element.h
  include/elements/2d/quadrilateral_bspline_element.tcc
  include/elements/2d/quadrilateral_element.h
  include/elements/2d/quadrilateral_element.tcc
  include/elements/2d/triangle_element.h
  include/elements/2d/triangle_element.tcc
  include/elements/3d/hexahedron_bspline_element.h
  include/elements/3d/hexahedron_bspline_element.tcc
  include/elements/3d/hexahedron_element.h
  include/elements/3d/hexahedron_element.tcc
  include/elements/3d/tetrahedron_element.h
  include/elements/3d/tetrahedron_element.tcc
  include/elements/element.h
  include/solvers/mpm_base.tcc
  tests/cells/cell_test.cc
  tests/elements/hexahedron_bspline_element_test.cc
  tests/elements/quadrilateral_bspline_element_test.cc
  tests/io/write_mesh_particles.cc
Labels: enhancement
