Repository geomechanics/mpm, pull requests merged in 2022-01, with the labels that each got.

#24 [Fix] Deprecated function and verbosity
  include/linear_solvers/convergence_criteria/convergence_criterion_residual.tcc
  include/linear_solvers/convergence_criteria/convergence_criterion_solution.tcc
  include/linear_solvers/linear_solvers/krylov_petsc.tcc
Labels: bug

#21 [Material] Small-strain elasto-plastic tangent matrix
  .circleci/config.yml
  include/materials/infinitesimal_elasto_plastic.h
  include/materials/infinitesimal_elasto_plastic.tcc
  include/materials/linear_elastic.h
  include/materials/linear_elastic.tcc
  include/materials/material.h
  include/materials/material_utility.h
  include/materials/material_utility.tcc
  include/materials/modified_cam_clay.h
  include/materials/modified_cam_clay.tcc
  include/materials/mohr_coulomb.h
  include/materials/mohr_coulomb.tcc
  include/materials/norsand.h
  include/materials/norsand.tcc
  include/particles/particle.h
  include/particles/particle_base.h
  include/particles/particle_implicit.tcc
  include/solvers/mpm_base.tcc
  include/solvers/mpm_implicit.tcc
  include/solvers/mpm_scheme/mpm_scheme_newmark.tcc
  tests/cells/cell_implicit_test.cc
  tests/io/write_mesh_particles.cc
  tests/io/write_mesh_particles_unitcell.cc
  tests/materials/bingham_test.cc
  tests/materials/linear_elastic_test.cc
  tests/materials/material_utility_test.cc
  tests/materials/modified_cam_clay_test.cc
  tests/materials/mohr_coulomb_test.cc
  tests/materials/newtonian_test.cc
  tests/materials/norsand_test.cc
Labels: enhancement

#14 [Element] Quadratic Bspline MPM
  CMakeLists.txt
  include/cells/cell.h
  include/cells/cell.tcc
  include/elements/2d/quadrilateral_bspline_element.h
  include/elements/2d/quadrilateral_bspline_element.tcc
  include/elements/2d/quadrilateral_element.h
  include/elements/2d/quadrilateral_element.tcc
  include/elements/2d/triangle_element.h
  include/elements/2d/triangle_element.tcc
  include/elements/3d/hexahedron_bspline_element.h
  include/elements/3d/hexahedron_bspline_element.tcc
  include/elements/3d/hexahedron_element.h
  include/elements/3d/hexahedron_element.tcc
  include/elements/element.h
  include/linear_solvers/assemblers/assembler_base.h
  include/linear_solvers/assemblers/assembler_base.tcc
  include/linear_solvers/assemblers/assembler_eigen_implicit.tcc
  include/linear_solvers/assemblers/assembler_eigen_semi_implicit_navierstokes.tcc
  include/linear_solvers/assemblers/assembler_eigen_semi_implicit_twophase.tcc
  include/mesh/mesh.h
  include/mesh/mesh.tcc
  include/nodes/node.h
  include/nodes/node.tcc
  include/nodes/node_base.h
  include/solvers/mpm.h
  include/solvers/mpm_base.h
  include/solvers/mpm_base.tcc
  include/solvers/mpm_explicit_twophase.tcc
  include/solvers/mpm_semi_implicit_twophase.tcc
  src/element.cc
  tests/cells/cell_test.cc
  tests/convergence_criteria_test.cc
  tests/elements/hexahedron_bspline_element_test.cc
  tests/elements/hexahedron_element_test.cc
  tests/elements/hexahedron_gimp_element_test.cc
  tests/elements/quadrilateral_bspline_element_test.cc
  tests/elements/quadrilateral_element_test.cc
  tests/elements/quadrilateral_gimp_element_test.cc
  tests/elements/triangle_element_test.cc
  tests/io/write_mesh_particles.cc
  tests/linear_solver_test.cc
  tests/mesh/mesh_neighbours_test.cc
  tests/mesh/mesh_test_2d.cc
  tests/mesh/mesh_test_3d.cc
Labels: enhancement

#30 [Bugfix] Reduction of dmatrix for 2D
  include/particles/particle_implicit.tcc
Labels: bug

#28 [Feature] Matrix noaliasing
  .circleci/config.yml
  include/cells/cell.tcc
  include/cells/cell_implicit.tcc
  include/cells/cell_multiphase.tcc
  include/elements/2d/quadrilateral_bspline_element.tcc
  include/elements/2d/quadrilateral_element.tcc
  include/elements/2d/triangle_element.tcc
  include/elements/3d/hexahedron_bspline_element.tcc
  include/elements/3d/hexahedron_element.tcc
  include/linear_solvers/assemblers/assembler_eigen_implicit.tcc
  include/linear_solvers/assemblers/assembler_eigen_semi_implicit_navierstokes.tcc
  include/linear_solvers/assemblers/assembler_eigen_semi_implicit_twophase.tcc
  include/linear_solvers/linear_solvers/krylov_petsc.h
  include/materials/mohr_coulomb.tcc
  include/mesh/mesh_multiphase.tcc
  include/nodes/node.tcc
  include/nodes/node_multiphase.tcc
  include/particles/particle.tcc
  include/particles/particle_fluid.tcc
  include/particles/particle_implicit.tcc
  include/particles/particle_twophase.tcc
  tests/particles/particle_test.cc
  tests/particles/particle_twophase_test.cc
Labels: enhancement, help wanted
